Repository Team-Swamp/IceBites, pull requests merged in 2024-03, with the labels that each got.

#20 feature/random-material-selector
  Assets/Scripts/Environment/RandomMaterialSelector.cs
  Assets/Scripts/Environment/RandomMaterialSelector.cs.meta
Labels: code, new, ready for merge

#21 feature/mobile-friendliness
  Assets/Prefabs/UI/MainCanvas.prefab
  Assets/Prefabs/UI/Progressbar.prefab
  Assets/Prefabs/UI/Progressbar.prefab.meta
  Assets/Prefabs/UI/SettingsScreen.prefab
  Assets/Prefabs/UI/SettingsScreen.prefab.meta
  Assets/Scenes/Main Menu.unity
  Assets/Scenes/NPC Testing.unity
  Assets/Scripts/Framework/SceneSwitcher.cs
  Assets/Scripts/UI/Menus/SettingsMenu.cs
  Assets/Scripts/UI/Menus/SwitchMenus.cs
  ProjectSettings/ProjectSettings.asset
Labels: bug, code, ready for merge, ready for testing

#22 feature/game-loop
  Assets/Prefabs/Cooking/Dishes.meta
  Assets/Prefabs/Cooking/Dishes/New Dish.prefab
  Assets/Prefabs/Cooking/Dishes/New Dish.prefab.meta
  Assets/Prefabs/Cooking/Dishes/Test Burger visual.prefab
  Assets/Prefabs/Cooking/Dishes/Test Burger visual.prefab.meta
  Assets/Prefabs/Cooking/Ingredients.meta
  Assets/Prefabs/Cooking/Ingredients/Base Ingredient.prefab
  Assets/Prefabs/Cooking/Ingredients/Base Ingredient.prefab.meta
  Assets/Prefabs/Cooking/Kitchen Appliances.meta
  Assets/Prefabs/Cooking/Kitchen Appliances/Base Kichten Appliance.prefab
  Assets/Prefabs/Cooking/Kitchen Appliances/Base Kichten Appliance.prefab.meta
  Assets/Prefabs/Cooking/Kitchen Appliances/Grill Variant.prefab
  Assets/Prefabs/Cooking/Kitchen Appliances/Grill Variant.prefab.meta
  Assets/Prefabs/Cooking/RecipesHolder.prefab
  Assets/Prefabs/Cooking/RecipesHolder.prefab.meta
  Assets/Prefabs/NPC/NPC walking.prefab
  Assets/Prefabs/NPC/NPC walking.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/Art.meta
  Assets/Scenes/Art/Lisa_VooDoo.unity
  Assets/Scenes/Art/Lisa_VooDoo.unity.meta
  Assets/Scenes/Boot scene.unity
  Assets/Scenes/Gameplay.unity
  Assets/Scenes/Gameplay.unity.meta
  Assets/Scenes/Main Menu.unity
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/Testing.meta
  Assets/Scenes/Testing/Ads.meta
  Assets/Scenes/Testing/Ads/Ads.unity
  Assets/Scenes/Testing/Ads/Ads.unity.meta
  Assets/Scenes/Testing/Interact Ray.unity
  Assets/Scenes/Testing/Interact Ray.unity.meta
  Assets/Scenes/Testing/NPC.meta
  Assets/Scenes/Testing/NPC/NPC Movement.unity
  Assets/Scenes/Testing/NPC/NPC Movement.unity.meta
  Assets/Scenes/Testing/NPC/NpcOrdering.unity
  Assets/Scenes/Testing/NPC/NpcOrdering.unity.meta
  Assets/Scripts/Framework/Cooking/DishManager.cs
  Assets/Scripts/Framework/Cooking/IngredientObject.cs
  Assets/Scripts/Framework/Cooking/KitchenAppliance.cs
  Assets/Scripts/UI/Menus/SettingsMenu.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: code, new, work in progress

#29 Feature/score system
  .gitignore
  Assets/Prefabs/System.meta
  Assets/Prefabs/System/ScoreManager.prefab
  Assets/Prefabs/System/ScoreManager.prefab.meta
  Assets/Prefabs/UI/MainCanvas.prefab
  Assets/Scenes/Testing/NPC/NpcScoreSystem.unity
  Assets/Scenes/Testing/NPC/NpcScoreSystem.unity.meta
  Assets/Scripts/Framework/ScoreManager.cs
  Assets/Scripts/Framework/ScoreManager.cs.meta
  Assets/Scripts/NPC/NpcOrdering.cs
Labels: code, new, ready for review

#30 Added lamp and new lighting
  Assets/Materials/Lamp.meta
  Assets/Materials/Lamp/M_Lamp.mat
  Assets/Materials/Lamp/M_Lamp.mat.meta
  Assets/Models/Lamp.meta
  Assets/Models/Lamp/SM_Lamp.fbx
  Assets/Models/Lamp/SM_Lamp.fbx.meta
  Assets/Prefabs/Eviroment/Lamp.prefab
  Assets/Prefabs/Eviroment/Lamp.prefab.meta
  Assets/Prefabs/Lighting.meta
  Assets/Prefabs/Lighting/Directional Light.prefab
  Assets/Prefabs/Lighting/Directional Light.prefab.meta
  Assets/Prefabs/Lighting/Spot Light (1).prefab
  Assets/Prefabs/Lighting/Spot Light (1).prefab.meta
  Assets/Scenes/Art/Lisa_VooDoo.meta
  Assets/Scenes/Art/Lisa_VooDoo.unity
  Assets/Textures/Lamp.meta
  Assets/Textures/Lamp/T_Lamp_D.png
  Assets/Textures/Lamp/T_Lamp_D.png.meta
  Assets/Textures/Lamp/T_Lamp_E.png
  Assets/Textures/Lamp/T_Lamp_E.png.meta
  Assets/Textures/Lamp/T_Lamp_H.png
  Assets/Textures/Lamp/T_Lamp_H.png.meta
  Assets/Textures/Lamp/T_Lamp_MT.png
  Assets/Textures/Lamp/T_Lamp_MT.png.meta
  Assets/Textures/Lamp/T_Lamp_N.png
  Assets/Textures/Lamp/T_Lamp_N.png.meta
  Assets/Textures/Lamp/T_Lamp_R.png
  Assets/Textures/Lamp/T_Lamp_R.png.meta
Labels: art, new, ready for merge

#32 Added Animations for penguin, replaced penguin placeholder with final model
  Assets/Animations/Penguin.meta
  Assets/Animations/Penguin/NPC.meta
  Assets/Animations/Penguin/NPC/Idle.anim
  Assets/Animations/Penguin/NPC/Idle.anim.meta
  Assets/Animations/Penguin/Player.meta
  Assets/Animations/Penguin/Player/AC_Penguin.controller
  Assets/Animations/Penguin/Player/AC_Penguin.controller.meta
  Assets/Animations/Penguin/Player/A_Idle Holding.anim
  Assets/Animations/Penguin/Player/A_Idle Holding.anim.meta
  Assets/Animations/Penguin/Player/A_Idle.anim
  Assets/Animations/Penguin/Player/A_Idle.anim.meta
  Assets/Animations/Penguin/Player/A_Npc Order.anim
  Assets/Animations/Penguin/Player/A_Npc Order.anim.meta
  Assets/Animations/Penguin/Player/A_Npc Sitting Idle.anim
  Assets/Animations/Penguin/Player/A_Npc Sitting Idle.anim.meta
  Assets/Animations/Penguin/Player/A_Npc Sitting.anim
  Assets/Animations/Penguin/Player/A_Npc Sitting.anim.meta
  Assets/Animations/Penguin/Player/A_Npc Standing up.anim
  Assets/Animations/Penguin/Player/A_Npc Standing up.anim.meta
  Assets/Animations/Penguin/Player/A_Walk Cycle Holding.anim
  Assets/Animations/Penguin/Player/A_Walk Cycle Holding.anim.meta
  Assets/Animations/Penguin/Player/A_Walk Cycle.anim
  Assets/Animations/Penguin/Player/A_Walk Cycle.anim.meta
  Assets/Materials/Penguin/M_Penguin_Body.mat
  Assets/Models/Penguin/Ch_Penguin.fbx
  Assets/Models/Penguin/Ch_Penguin.fbx.meta
  Assets/Models/Penguin/Penguin met animaties.fbx
  Assets/Models/Penguin/Penguin met animaties.fbx.meta
  Assets/Scenes/Dylan_VooDoo.unity
  Assets/Textures/Penguin/NPC/T_Penguin_Body_D.png
  Assets/Textures/Penguin/NPC/T_Penguin_Body_D.png.meta
Labels: art, new

#35 Added Material, Model, Textures and Prefab For Cupcake
  Assets/Materials/Gerechten/M_Cupcake_Dough.mat
  Assets/Materials/Gerechten/M_Cupcake_Dough.mat.meta
  Assets/Materials/Gerechten/M_Cupcake_Frosting.mat
  Assets/Materials/Gerechten/M_Cupcake_Frosting.mat.meta
  Assets/Materials/Gerechten/M_Cupcake_Paper.mat
  Assets/Materials/Gerechten/M_Cupcake_Paper.mat.meta
  Assets/Models/Gerechten/SM_Cupcake.fbx
  Assets/Models/Gerechten/SM_Cupcake.fbx.meta
  Assets/Prefabs/Gerechten/Cupcake.prefab
  Assets/Prefabs/Gerechten/Cupcake.prefab.meta
  Assets/Scenes/Dylan_VooDoo.unity
  Assets/Textures/Gerechten.meta
  Assets/Textures/Gerechten/T_Cupcake_Dough_D.png
  Assets/Textures/Gerechten/T_Cupcake_Dough_D.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Dough_MT.png
  Assets/Textures/Gerechten/T_Cupcake_Dough_MT.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Dough_N.png
  Assets/Textures/Gerechten/T_Cupcake_Dough_N.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Frosting_D.png
  Assets/Textures/Gerechten/T_Cupcake_Frosting_D.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Frosting_MT.png
  Assets/Textures/Gerechten/T_Cupcake_Frosting_MT.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Frosting_N.png
  Assets/Textures/Gerechten/T_Cupcake_Frosting_N.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Paper_D.png
  Assets/Textures/Gerechten/T_Cupcake_Paper_D.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Paper_MT.png
  Assets/Textures/Gerechten/T_Cupcake_Paper_MT.png.meta
  Assets/Textures/Gerechten/T_Cupcake_Paper_N.png
  Assets/Textures/Gerechten/T_Cupcake_Paper_N.png.meta
Labels: art, new, ready for merge

#37 Added orderbubble
  Assets/Scenes/Art/Lisa_VooDoo.unity
  Assets/Sprites/Orderbubble.meta
  Assets/Sprites/Orderbubble/T_Burger.png
  Assets/Sprites/Orderbubble/T_Burger.png.meta
  Assets/Sprites/Orderbubble/T_Cupcake.png
  Assets/Sprites/Orderbubble/T_Cupcake.png.meta
  Assets/Sprites/Orderbubble/T_Orderbubble.png
  Assets/Sprites/Orderbubble/T_Orderbubble.png.meta
  Assets/Sprites/Orderbubble/T_Sushi.png
  Assets/Sprites/Orderbubble/T_Sushi.png.meta
  Assets/Sprites/Orderbubble/T_Taco.png
  Assets/Sprites/Orderbubble/T_Taco.png.meta
Labels: art, new, ready for merge

#34 Feature/Animation-Controller
  Assets/Animations/Penguin/NPC/AC_Penguin.controller
  Assets/Animations/Penguin/NPC/AC_Penguin.controller.meta
  Assets/Animations/Penguin/NPC/A_Idle Holding.anim
  Assets/Animations/Penguin/NPC/A_Idle Holding.anim.meta
  Assets/Animations/Penguin/NPC/A_Idle.anim
  Assets/Animations/Penguin/NPC/A_Idle.anim.meta
  Assets/Animations/Penguin/NPC/A_Npc Order.anim
  Assets/Animations/Penguin/NPC/A_Npc Order.anim.meta
  Assets/Animations/Penguin/NPC/A_Npc Sitting Idle.anim
  Assets/Animations/Penguin/NPC/A_Npc Sitting Idle.anim.meta
  Assets/Animations/Penguin/NPC/A_Npc Sitting.anim
  Assets/Animations/Penguin/NPC/A_Npc Sitting.anim.meta
  Assets/Animations/Penguin/NPC/A_Npc Standing up.anim
  Assets/Animations/Penguin/NPC/A_Npc Standing up.anim.meta
  Assets/Animations/Penguin/NPC/A_Walk Cycle Holding.anim
  Assets/Animations/Penguin/NPC/A_Walk Cycle Holding.anim.meta
  Assets/Animations/Penguin/NPC/A_Walk Cycle.anim
  Assets/Animations/Penguin/NPC/A_Walk Cycle.anim.meta
  Assets/Prefabs/NPC/PenguinAnimation.prefab
  Assets/Prefabs/NPC/PenguinAnimation.prefab.meta
  Assets/Scenes/Gameplay.unity
  Assets/Scripts/Framework/Animation.meta
  Assets/Scripts/Framework/Animation/AnimationController.cs
  Assets/Scripts/Framework/Animation/AnimationController.cs.meta
  Assets/Scripts/Framework/GridPoints/NpcPoints.cs
  Assets/Scripts/Framework/GridPoints/PlayerPoints.cs
  Assets/Scripts/NPC/NpcMovement.cs
  Assets/Scripts/NPC/NpcOrdering.cs
Labels: code, new

#39 Changed the windows and cupcake display
  Assets/Materials/Bar/M_Vetrine.mat
  Assets/Models/Enviroment/SM_Enviroment.fbx
  Assets/Models/Enviroment/SM_Enviroment.fbx.meta
  Assets/Prefabs/Eviroment/Enviroment.prefab
  Assets/Prefabs/Eviroment/Enviroment.prefab.meta
  Assets/Scenes/Art/Lisa_VooDoo.unity
Labels: art, ready for merge

#33 feature/held-item
  Assets/Prefabs/Cooking/Dishes/Gerechten.meta
  Assets/Prefabs/Cooking/Dishes/Gerechten/Cupcake.prefab
  Assets/Prefabs/Cooking/Dishes/Gerechten/Cupcake.prefab.meta
  Assets/Prefabs/Cooking/Dishes/Gerechten/Fish Burger.prefab
  Assets/Prefabs/Cooking/Dishes/Gerechten/Fish Burger.prefab.meta
  Assets/Prefabs/Cooking/Dishes/Gerechten/Fish Taco.prefab
  Assets/Prefabs/Cooking/Dishes/Gerechten/Fish Taco.prefab.meta
  Assets/Prefabs/Cooking/Dishes/Gerechten/Sushi.prefab
  Assets/Prefabs/Cooking/Dishes/Gerechten/Sushi.prefab.meta
  Assets/Prefabs/Cooking/Dishes/Test Burger visual.prefab
  Assets/Prefabs/Cooking/Ingredients/Base Ingredient.prefab
  Assets/Prefabs/Cooking/Ingredients/Bread Variant.prefab
  Assets/Prefabs/Cooking/Ingredients/Bread Variant.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/Ingredieten.meta
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Burger Bread.prefab
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Burger Bread.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Cooked Fish Variant.prefab
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Cooked Fish Variant.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Raw Fish.prefab
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Raw Fish.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Seaweed.prefab
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Seaweed.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Taco Shell.prefab
  Assets/Prefabs/Cooking/Ingredients/Ingredieten/Taco Shell.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/RawFish Variant.prefab
  Assets/Prefabs/Cooking/Ingredients/RawFish Variant.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/SeaWeed Variant.prefab
  Assets/Prefabs/Cooking/Ingredients/SeaWeed Variant.prefab.meta
  Assets/Prefabs/Cooking/Ingredients/TacoShell Variant.prefab
  Assets/Prefabs/Cooking/Ingredients/TacoShell Variant.prefab.meta
  Assets/Prefabs/Cooking/Kitchen Appliances/Base Kichten Appliance.prefab
  Assets/Prefabs/Cooking/Kitchen Appliances/Basket.prefab
  Assets/Prefabs/Cooking/Kitchen Appliances/Basket.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Testing/HeldItems.unity
  Assets/Scenes/Testing/HeldItems.unity.meta
  Assets/ScriptableObjects/Repices/FishBurger.asset
  Assets/ScriptableObjects/Repices/FishTaco.asset
  Assets/ScriptableObjects/Repices/Shusi.asset
  Assets/Scripts/Framework/BaseMovement.cs
  Assets/Scripts/Framework/Cooking/DishManager.cs
  Assets/Scripts/Framework/Cooking/HeldItem.cs
  Assets/Scripts/Framework/Cooking/HeldItem.cs.meta
  Assets/Scripts/Framework/Cooking/IngredientBasket.cs
  Assets/Scripts/Framework/Cooking/IngredientBasket.cs.meta
  Assets/Scripts/Framework/Cooking/IngredientObject.cs
  Assets/Scripts/Framework/Cooking/KitchenAppliance.cs
  Assets/Scripts/Framework/Enums/GridPoints.meta
  Assets/Scripts/Framework/Enums/GridPoints/NpcPoints.cs
  Assets/Scripts/Framework/Enums/GridPoints/NpcPoints.cs.meta
  Assets/Scripts/Framework/Enums/GridPoints/PlayerPoints.cs
  Assets/Scripts/Framework/Enums/GridPoints/PlayerPoints.cs.meta
  Assets/Scripts/Player/Input Parser/InputParser.cs
  Assets/Scripts/Player/ItemHolding.cs
  Assets/Scripts/Player/ItemHolding.cs.meta
Labels: code, new, ready for review

#40 Art/game-icon
  Assets/Sprites/T_GameIcon.png
  Assets/Sprites/T_GameIcon.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: art, new, ready for merge

#41 Added UI and Bestek placement
  Assets/Scenes/Art/Lisa_VooDoo.unity
  Assets/Sprites/Orderbubble/T_Coffee.png
  Assets/Sprites/Orderbubble/T_Coffee.png.meta
  Assets/Sprites/Orderbubble/T_Smoothie.png
  Assets/Sprites/Orderbubble/T_Smoothie.png.meta
  Assets/Sprites/Orderbubble/T_Thea.png
  Assets/Sprites/Orderbubble/T_Thea.png.meta
  Assets/Sprites/Orderbubble/T_Water.png
  Assets/Sprites/Orderbubble/T_Water.png.meta
Labels: art, new, ready for review
