Repository Team-Swamp/IceBites, pull requests merged in 2024-02, with the labels that each got.

#1 Feature/extensions
  Assets/Scenes/Boot scene.unity
  Assets/Scenes/Boot scene.unity.meta
  Assets/Scripts/Framework/Attributes.meta
  Assets/Scripts/Framework/Attributes/CharValue.cs
  Assets/Scripts/Framework/Attributes/CharValue.cs.meta
  Assets/Scripts/Framework/Attributes/StringValue.cs
  Assets/Scripts/Framework/Attributes/StringValue.cs.meta
  Assets/Scripts/Framework/Attributes/Vector2Value.cs
  Assets/Scripts/Framework/Attributes/Vector2Value.cs.meta
  Assets/Scripts/Framework/Attributes/Vector3Value.cs
  Assets/Scripts/Framework/Attributes/Vector3Value.cs.meta
  Assets/Scripts/Framework/Extensions.meta
  Assets/Scripts/Framework/Extensions/EnumExtensions.cs
  Assets/Scripts/Framework/Extensions/EnumExtensions.cs.meta
  Assets/Scripts/Framework/Extensions/VectorExtensions.cs
  Assets/Scripts/Framework/Extensions/VectorExtensions.cs.meta
  Assets/Scripts/Framework/SceneSwitcher.cs
  Assets/Scripts/Framework/SceneSwitcher.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/SceneTemplateSettings.json
Labels: code, new, ready for review

#2 feature/timer
  Assets/Scripts/Framework/Extensions/EnumExtensions.cs
  Assets/Scripts/Framework/Timer.cs
  Assets/Scripts/Framework/Timer.cs.meta
Labels: code, new, ready for review

#3 Feature/Grid-System/PlayerMovement
  Assets/Input.meta
  Assets/Input/Player Input.inputactions
  Assets/Input/Player Input.inputactions.meta
  Assets/Scenes/Grid-System-Test.unity
  Assets/Scenes/Grid-System-Test.unity.meta
  Assets/Scripts/Framework/Attributes/Vector2Value.cs
  Assets/Scripts/Framework/Attributes/Vector3Value.cs
  Assets/Scripts/Framework/GridSystem.meta
  Assets/Scripts/Framework/GridSystem/GridList.cs
  Assets/Scripts/Framework/GridSystem/GridList.cs.meta
  Assets/Scripts/Player/Input Parser.meta
  Assets/Scripts/Player/Input Parser/InputParser.cs
  Assets/Scripts/Player/Input Parser/InputParser.cs.meta
  Assets/Scripts/Player/Movement.meta
  Assets/Scripts/Player/Movement/PlayerMovement.cs
  Assets/Scripts/Player/Movement/PlayerMovement.cs.meta
Labels: code, new, ready for review

#6 hotfix/sealed-classes
  Assets/Scripts/Player/Input Parser/InputParser.cs
  Assets/Scripts/Player/Movement/PlayerMovement.cs
Labels: code, ready for review

#4 feature/npc-ordering
  Assets/Editor/TimerEditor.cs
  Assets/Editor/TimerEditor.cs.meta
  Assets/Prefabs/NPC.meta
  Assets/Prefabs/NPC/TestingNPC.prefab
  Assets/Prefabs/NPC/TestingNPC.prefab.meta
  Assets/Scenes/NPC.meta
  Assets/Scenes/NPC/NpcOrdering.unity
  Assets/Scenes/NPC/NpcOrdering.unity.meta
  Assets/ScriptableObjects/Empty.asset
  Assets/ScriptableObjects/Empty.asset.meta
  Assets/ScriptableObjects/Order.asset
  Assets/ScriptableObjects/Order.asset.meta
  Assets/Scripts/Framework/Enums/Dish.cs
  Assets/Scripts/Framework/Enums/Dish.cs.meta
  Assets/Scripts/Framework/Extensions/EnumExtensions.cs
  Assets/Scripts/Framework/ScriptableObjects.meta
  Assets/Scripts/Framework/ScriptableObjects/NpcOrder.cs
  Assets/Scripts/Framework/ScriptableObjects/NpcOrder.cs.meta
  Assets/Scripts/Framework/Timer.cs
  Assets/Scripts/NPC/NpcOrdering.cs
  Assets/Scripts/NPC/NpcOrdering.cs.meta
  Assets/Scripts/Player/TestGiveGetOrder.cs
  Assets/Scripts/Player/TestGiveGetOrder.cs.meta
Labels: code, new, ready for review, ready for testing

#8 art/blockout
  Assets/Models/Blockout.fbx
  Assets/Models/Blockout.fbx.meta
Labels: art, new, ready for merge, ready for testing

#7 Feature/NPC-movement
  Assets/Scenes/Grid-System-Test.unity
  Assets/Scenes/NPC Testing.unity
  Assets/Scenes/NPC Testing.unity.meta
  Assets/Scripts/Framework/BaseMovement.cs
  Assets/Scripts/Framework/BaseMovement.cs.meta
  Assets/Scripts/Framework/GridPoints.meta
  Assets/Scripts/Framework/GridPoints/NpcPoints.cs
  Assets/Scripts/Framework/GridPoints/NpcPoints.cs.meta
  Assets/Scripts/Framework/GridPoints/PlayerPoints.cs
  Assets/Scripts/Framework/GridPoints/PlayerPoints.cs.meta
  Assets/Scripts/Framework/GridSystem/GridList.cs
  Assets/Scripts/NPC/NpcMovement.cs
  Assets/Scripts/NPC/NpcMovement.cs.meta
  Assets/Scripts/Player/Input Parser/InputParser.cs
  Assets/Scripts/Player/Movement/PlayerMovement.cs
Labels: code, new

#9 Feature/ad system
  Assets/Editor/TimerEditor.cs
  Assets/Prefabs/UI.meta
  Assets/Prefabs/UI/MainCanvas.prefab
  Assets/Prefabs/UI/MainCanvas.prefab.meta
  Assets/Scenes/Ads.meta
  Assets/Scenes/Ads/Ads.unity
  Assets/Scenes/Ads/Ads.unity.meta
  Assets/Scripts/Framework/Extensions/EnumExtensions.cs
  Assets/Scripts/Framework/SceneSwitcher.cs
  Assets/Scripts/Framework/Structs/TimerData.cs
  Assets/Scripts/Framework/Structs/TimerData.cs.meta
  Assets/Scripts/Framework/Timer.cs
  Assets/Scripts/UI/Ads.meta
  Assets/Scripts/UI/Ads/AdSystem.cs
  Assets/Scripts/UI/Ads/AdSystem.cs.meta
  Assets/Scripts/UI/Ads/CrossButton.cs
  Assets/Scripts/UI/Ads/CrossButton.cs.meta
  Assets/Sprites/Ads.meta
  Assets/Sprites/Ads/FakeAd-LostReel.png
  Assets/Sprites/Ads/FakeAd-LostReel.png.meta
  Assets/TextMesh Pro.meta
Labels: code, new, ready for review, ready for testing

#12 Added SetAndLoadScene method
  Assets/Scripts/Framework/SceneSwitcher.cs
Labels: code, new, ready for review

#14 Menu's
  Assets/Audio.meta
  Assets/Audio/MasterVolume.mixer
  Assets/Audio/MasterVolume.mixer.meta
  Assets/Input/Player Input.inputactions
  Assets/Prefabs/UI/MainCanvas.prefab
  Assets/Scenes/Boot scene.unity
  Assets/Scenes/Main Menu.unity
  Assets/Scenes/Main Menu.unity.meta
  Assets/Scenes/NPC Testing.unity
  Assets/Scripts/Framework/SceneSwitcher.cs
  Assets/Scripts/Player/Input Parser/InputParser.cs
  Assets/Scripts/UI/Menus.meta
  Assets/Scripts/UI/Menus/SettingsMenu.cs
  Assets/Scripts/UI/Menus/SettingsMenu.cs.meta
  Assets/Scripts/UI/Menus/SwitchMenus.cs
  Assets/Scripts/UI/Menus/SwitchMenus.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TimelineSettings.asset
Labels: code, new, ready for testing

#13 object-interact
  Assets/Input/Player Input.inputactions
  Assets/Scenes/Interact Ray.unity
  Assets/Scenes/Interact Ray.unity.meta
  Assets/Scripts/Framework/InteractableObject.cs
  Assets/Scripts/Framework/InteractableObject.cs.meta
  Assets/Scripts/Player/Input Parser/InputParser.cs
  ProjectSettings/TagManager.asset
Labels: code, new, work in progress

#17 Hotfix/Npc-Movement
  Assets/Scripts/NPC/NpcMovement.cs
Labels: bug, code, ready for review

#18 hotfix/mobile-build
  Assets/Scenes/Boot scene.unity
  Assets/Scenes/Main Menu.unity
  ProjectSettings/BurstAotSettings_Android.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: bug, ready for review
